name: sto_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">2.10.0"

dependencies:
  flutter:
    sdk: flutter
  splashscreen:
  material_design_icons_flutter: ^4.0.5755
  flutter_svg: ^0.19.1
  cloud_firestore: ^0.14.4
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  flutter_spinkit: ^4.1.2+1
  carousel_slider: ^1.3.0
  cupertino_icons: ^1.0.0
  hexcolor:
  image_picker: ^0.6.0+9
  shared_preferences: ^0.5.12+4
  http: ^0.12.2
  connectivity: ^2.0.2
  dio:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/categories/
    - assets/services.json
    - assets/cars_model.json
  fonts:
    - family:  Stoappicons
      fonts:
       - asset: fonts/Stoappicons.ttf
    - family: Montserrat Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Montserrat Medium
      fonts:    
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: Montserrat SemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700